### PR TITLE
BVAL-558 Make two synchronized methods of Validation.GetValidationPro…

### PR DESCRIPTION
**Pull request by kasabuta4**
…viderListAction static

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hi, thanks for opening this pull request. Its reational is not quite clear to me, though. I.e. what do we gain by making these methods static?

**Comment by kasabuta4** [comment]
Thanks, two synchronized methods want to synchronize access to `providersPerClassloader` static field.
But they are currently instance methods, so they synchronize access to each `GetValidationProviderListAction` instance, not access to `providersPerClassloader`.
Making these methods static synchronize access to `providersPerClassloader`.

**Comment by kasabuta4** [comment]
Let me explain a little more in detail.

Suppose two threads, _Thread-A_ and _Thread-B_, invoke `GetValidationProviderListAction#getValidationProviderList()` at the same time.

_Thread-A_ instantiates a `GetValidationProviderListAction` object, _Action-A_, and invokes _Action-A_’s `run()` method.
Then, _Action-A_’s `run()` invokes `getCachedValidationProviders(ClassLoader)` instance method which acquires the monitor of _Action-A_ object.

At the same time, _Thread-B_ instantiates a `GetValidationProviderListAction` object, _Action-B_, and invokes _Action-B_’s `run()` method.
Then, _Action-B_’s `run()` invokes `getCachedValidationProviders(ClassLoader)` instance method which acquires the monitor of _Action-B_ object with no problem.

Although `getCachedValidationProviders(ClassLoader)` method is synchronized, each thread instantiates and locks its own object(_Thread-A_ instantiates and locks _Action-A_, _Thread-B_ does _Action-B_), so synchronization actually has no effect.

Making `getCachedValidationProviders(ClassLoader)` method static changes lock target to `GetValidationProviderListAction` class object, so it prevents more than one execution at a time.

**Comment by gunnarmorling** [comment]
Thanks, got it :) Good catch!

**Comment by gunnarmorling** [comment]
So I went for a slightly different approach, see PR #80, thus I'm going to close this one.

There is only one `GetValidationProviderListAction` instance ever now, ensuring correct access and avoiding some instantiations. Can you check it out and let me know whether you see any further issues? 

Thanks!

**Pull request closed without merging**
