### PR TITLE
BVAL-509 Making JavaDoc happy

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by emmanuelbernard** [comment]
@gunnarmorling So that's the only requirement (JavaDoc fixes)?. No need for some module mojo?

**Comment by gunnarmorling** [comment]
That's it for compilation, I haven't looked into module stuff (there's
separate issue for that).

**Comment by emmanuelbernard** [comment]
```
Javadoc Warnings
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/ConstraintValidatorContext.java:116: warning: empty <p> tag
* <p>
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/ConstraintValidatorContext.java:165: warning: no @param for <T>
<T> T unwrap(Class<T> type);
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/ConstraintValidatorFactory.java:35: warning: no @param for <T>
<T extends ConstraintValidator<?, ?>> T getInstance(Class<T> key);
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/ConstraintViolation.java:148: warning: no @param for <U>
<U> U unwrap(Class<U> type);
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/MessageInterpolator.java:84: warning: no @param for <T>
<T> T unwrap(Class<T> type);
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/Validation.java:141: warning: empty <p> tag
* <p>
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/Validation.java:159: warning: no @param for <T>
ProviderSpecificBootstrap<T> byProvider(Class<U> providerType) {
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/Validation.java:159: warning: no @param for <U>
ProviderSpecificBootstrap<T> byProvider(Class<U> providerType) {
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/Validator.java:46: warning: no @param for <T>
<T> Set<ConstraintViolation<T>> validate(T object, Class<?>... groups);
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/Validator.java:63: warning: no @param for <T>
<T> Set<ConstraintViolation<T>> validateProperty(T object,
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/Validator.java:86: warning: no @param for <T>
<T> Set<ConstraintViolation<T>> validateValue(Class<T> beanType,
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/Validator.java:117: warning: no @param for <T>
<T> T unwrap(Class<T> type);
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/ValidatorFactory.java:99: warning: no @param for <T>
public <T> T unwrap(Class<T> type);
^
/Users/emmanuel/Code/beanvalidation/validation-api/src/main/java/javax/validation/executable/ValidateOnExecution.java:77: warning: no @return
ExecutableType[] type() default {ExecutableType.IMPLICIT};
```

**Comment by gunnarmorling** [comment]
Merged. Created https://hibernate.atlassian.net/browse/BVAL-510 as follow-up for the final clean-up/copying into the spec text.

**Pull request closed without merging**
