### PR TITLE
BVAL-561 Make @OverridesAttribute repeatable and documented

### PR DESCRIPTION
**Pull request by kasabuta4**
https://hibernate.atlassian.net/projects/BVAL/issues/BVAL-561

### CODE REVIEW

**Comment by gunnarmorling** [comment]
ok to test

**Comment by hendrikebbers** [comment]
LGTM

**Comment by chkal** [comment]
+1 for merging

**Comment by gunnarmorling** [comment]
Merged; thanks, @kasabuta4!

**Pull request closed without merging**
