### PR TITLE
Fix javadoc warnings

### PR DESCRIPTION
**Pull request by hendrikebbers**
See https://hibernate.atlassian.net/browse/BVAL-532

The order of some imports changes with this PR. Is there any specific configuration for IntelliJ?

### CODE REVIEW

**Comment by gsmet** [comment]
Hi Hendrik,

Is it any different from what I did in the last commit of https://github.com/beanvalidation/beanvalidation-api/pull/60/commits ?

**Comment by hendrikebbers** [comment]
Lol, no 
Found this on the issue tracker and thought this will be an easy one. But I did this after I reviewed your PR. 😆 Looks like I need some sleep

**Comment by gsmet** [comment]
There is an Assignee field at the right of the JIRA issue. If there's someone there, it's probably that's it's being worked on!

Thanks anyway!

**Comment by hendrikebbers** [comment]
Makes sense :) I had a look at all "open" issues.

**Pull request closed without merging**
