### PR TITLE
Initial text for readme

### PR DESCRIPTION
**Pull request by hendrikebbers**
added readme.md and initial text

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Merged; thanks, @hendrikebbers! Actually, some more info should be added: Instructions on how to build, pointers to some related resources and so on. The README.md from the RI may provide some inspiration: https://github.com/hibernate/hibernate-validator

**Comment by gsmet** [comment]
I wouldn't mind it to be renamed to README.md (uppercased) when new information are added to be consistent with what we did for the RI.

**Comment by gunnarmorling** [comment]
+1.

**Comment by gsmet** [comment]
@hendrikebbers do you plan to propose a follow-up PR with more information or should I take it from there?

Thanks for your feedback.

**Comment by hendrikebbers** [comment]
Hi,
finished work for today and will not continue before Monday

Cheers,

Hendrik

Von meinem iPhone gesendet

**Pull request merged**
